version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: filewalker
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: demo:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8080:8080